# Generated by Django 6.1 on 2026-09-01 14:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_nome', models.CharField(max_length=100, unique=True, verbose_name='Categoria')),
            ],
            options={
                'db_table': 'tb_acheiobug_categoria',
            },
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_nome', models.CharField(max_length=100, unique=True, verbose_name='Marca')),
            ],
            options={
                'db_table': 'tb_acheiobug_marca',
            },
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_nome', models.CharField(max_length=100, unique=True, verbose_name='Modelo')),
                ('fk_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.marca', verbose_name='Marca')),
            ],
            options={
                'db_table': 'tb_acheiobug_modelo',
            },
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_placa', models.CharField(max_length=7, unique=True, verbose_name='Placa')),
                ('st_cor', models.CharField(max_length=20, verbose_name='Cor')),
                ('dt_ano_fabricacao', models.DateField(verbose_name='Ano de Fabricação')),
                ('dt_ano_modelo', models.DateField(verbose_name='Ano do Modelo')),
                ('fk_marca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.marca', verbose_name='Marca')),
                ('fk_modelo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='veiculos.modelo', verbose_name='Modelo')),
            ],
            options={
                'db_table': 'tb_acheiobug_veiculo',
            },
        ),
    ]
