# Generated by Django 6.1 on 2026-09-01 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelo',
            name='st_nome',
            field=models.CharField(max_length=100, verbose_name='Modelo'),
        ),
    ]
