# Generated by Django 6.1 on 2026-09-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0002_alter_modelo_st_nome'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modelo',
            constraint=models.UniqueConstraint(fields=('st_nome', 'fk_marca'), name='unique_modelo_marca'),
        ),
    ]
