# Generated by Django 6.1 on 2026-09-04 13:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veiculos', '0003_modelo_unique_modelo_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='dt_ano_fabricacao',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2027)], verbose_name='Ano de Fabricação'),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='dt_ano_modelo',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1886), django.core.validators.MaxValueValidator(2027)], verbose_name='Ano do Modelo'),
        ),
    ]
