# Generated by Django 6.1 on 2026-08-20 14:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pessoas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orgao',
            fields=[
                ('pk_id', models.AutoField(primary_key=True, serialize=False)),
                ('st_sigla', models.CharField(max_length=100)),
                ('st_descricao', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'tb_acheiobug_orgao',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fk_nivel', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group')),
                ('fk_orgao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Orgao', to='pessoas.orgao')),
                ('fk_user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tb_acheiobug_usuario',
            },
        ),
        migrations.DeleteModel(
            name='Pessoa',
        ),
        migrations.CreateModel(
            name='UsuarioInterno',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.usuario')),
                ('st_cpf', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('st_foto', models.ImageField(blank=True, upload_to='uploads/imagens/%Y/%m/%d')),
                ('st_contato', models.CharField(blank=True, max_length=30, null=True)),
                ('bo_questionamento_whatsapp', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'tb_acheiobug_usuariointerno',
            },
            bases=('pessoas.usuario',),
        ),
        migrations.CreateModel(
            name='UsuarioRoot',
            fields=[
                ('usuario_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pessoas.usuario')),
                ('st_anexo_comprovante_autorizacao', models.FileField(upload_to='uploads/anexos/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'tb_acheiobug_usuarioroot',
            },
            bases=('pessoas.usuario',),
        ),
    ]
