# Generated by Django 6.1 on 2026-08-26 14:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('pessoas', '0002_orgao_usuario_delete_pessoa_usuariointerno_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='fk_nivel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.group', verbose_name='Nível'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fk_orgao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='Orgao', to='pessoas.orgao', verbose_name='Orgão'),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fk_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='usuariointerno',
            name='bo_questionamento_whatsapp',
            field=models.BooleanField(default=False, verbose_name='Questionamento Whatsapp'),
        ),
        migrations.AlterField(
            model_name='usuariointerno',
            name='st_contato',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Contato'),
        ),
        migrations.AlterField(
            model_name='usuariointerno',
            name='st_cpf',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
        migrations.AlterField(
            model_name='usuariointerno',
            name='st_foto',
            field=models.ImageField(blank=True, upload_to='uploads/imagens/%Y/%m/%d', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='usuarioroot',
            name='st_anexo_comprovante_autorizacao',
            field=models.FileField(upload_to='uploads/anexos/%Y/%m/%d/', verbose_name='Anexo comprovante de autorização'),
        ),
    ]
